"""
Purpose:
Manages communication with the ai-intelligence microservice.

Responsibilities:
- Defines the interface for sending QuestionStrategy payloads to AI generation.
- (MOCK) Simulates HTTP POST requests to the internal ai-intelligence endpoint.
- Protects the interview-agent from containing direct LLM invocation logic.

Connected Files:
- app/schemas/domain.py
"""

from app.schemas.domain import QuestionStrategy


class AIIntelligenceClient:
    """
    Client for interacting with the ai-intelligence API surface.
    In a real environment, this would use an HTTP client (like httpx or requests) 
    to POST /internal/ai/generate-question.
    """
    
    def __init__(self, base_url: str = "http://ai-intelligence-svc:8000"):
        self.base_url = base_url
        
    def generate_question_from_strategy(self, strategy: QuestionStrategy) -> str:
        """
        Sends the deterministic QuestionStrategy to the AI intelligence module
        which handles semantic retrieval, prompt formatting, and LLM inference.
        
        Returns:
            The raw natural language question generated by the AI.
        """
        # Mocking the AI response for the hackathon integration contract
        # In the future, this is: requests.post(f"{self.base_url}/internal/ai/generate-question", json=strategy.model_dump())
        
        mock_generated_wording = (
            f"[MOCK] This is an auto-generated {strategy.difficulty.value} question about {strategy.topic} "
            f"for a {strategy.candidate_tier.value} {strategy.candidate_job_role}. "
            f"Please explain the concepts: {', '.join(strategy.concepts)}."
        )
        
        return mock_generated_wording
