"""
Purpose:
Unit tests for the adaptive follow-up generation pipeline.

Responsibilities:
- Verify that previous answers are correctly appended to the history.
- Ensure retrieval filters and queries use the weak concepts.
- Verify fallback behavior handles LLM network failures safely.
- Test empty answers don't break the pipeline.

Connected Files:
- app/services/followup_generator.py
- app/schemas/question.py

Important implementation notes:
- Uses heavily mocked `retrieve` and `generate_structured_output`.
"""

import pytest
from unittest.mock import MagicMock, patch

from app.schemas.question import FollowUpStrategy, GeneratedQuestion
from app.services.followup_generator import generate_followup_question
from app.schemas.retrieval import RetrievalResult, RetrievedChunk


@pytest.fixture
def sample_followup_strategy():
    return FollowUpStrategy(
        day=6,
        topic="Vector Databases",
        weakConcepts=["cosine similarity", "dimensions"],
        reasoningGaps="Candidate mentioned vectors but couldn't explain how similarity is calculated."
    )


@patch("app.services.followup_generator.retrieve")
@patch("app.services.followup_generator.generate_structured_output")
def test_generate_followup_success(mock_generate, mock_retrieve, sample_followup_strategy):
    # Mock retrieval
    mock_retrieve.return_value = RetrievalResult(
        query="Vector Databases cosine similarity dimensions",
        total_found=1,
        chunks=[RetrievedChunk(content="Cosine similarity is used for...", score=0.9, metadata={"title": "Math"})]
    )
    
    # Mock LLM Output
    expected = GeneratedQuestion(
        question="Can you elaborate on how cosine similarity works?",
        type="technical",
        difficulty="hard",
        topic="Vector Databases",
        expectedConcepts=["angle", "magnitude"]
    )
    mock_generate.return_value = expected
    
    mock_llm = MagicMock()
    mock_qdrant = MagicMock()
    
    result = generate_followup_question(
        strategy=sample_followup_strategy,
        previous_answer="I use vectors to search.",
        candidate_context={},
        conversation_history=[{"role": "system", "content": "hello"}],
        llm_provider=mock_llm,
        qdrant_client=mock_qdrant
    )
    
    assert result.question == "Can you elaborate on how cosine similarity works?"
    assert result.type == "follow-up"
    
    # Verify the previous answer was appended
    kwargs = mock_generate.call_args.kwargs
    # The history_with_answer gets embedded inside the payload generated by build_followup_prompt
    # We can inspect that `generate_structured_output` was called.
    assert mock_generate.call_count == 1
    assert mock_retrieve.call_count == 1
    assert mock_retrieve.call_args.kwargs["filters"] == {"day": 6}


@patch("app.services.followup_generator.retrieve")
@patch("app.services.followup_generator.generate_structured_output")
def test_generate_followup_empty_answer(mock_generate, mock_retrieve, sample_followup_strategy):
    mock_retrieve.return_value = RetrievalResult(query="test", total_found=0, chunks=[])
    
    expected = GeneratedQuestion(
        question="You didn't answer, can you try?",
        type="technical",
        difficulty="easy",
        topic="Vector Databases",
        expectedConcepts=[]
    )
    mock_generate.return_value = expected
    
    result = generate_followup_question(
        strategy=sample_followup_strategy,
        previous_answer="   ", # Empty answer
        candidate_context={},
        conversation_history=[],
        llm_provider=MagicMock(),
        qdrant_client=MagicMock()
    )
    
    assert result.question == "You didn't answer, can you try?"


@patch("app.services.followup_generator.retrieve")
@patch("app.services.followup_generator.generate_structured_output")
def test_generate_followup_llm_failure(mock_generate, mock_retrieve, sample_followup_strategy):
    mock_retrieve.return_value = RetrievalResult(query="test", total_found=0, chunks=[])
    mock_generate.side_effect = Exception("LLM connection completely failed")
    
    result = generate_followup_question(
        strategy=sample_followup_strategy,
        previous_answer="I don't know.",
        candidate_context={},
        conversation_history=[],
        llm_provider=MagicMock(),
        qdrant_client=MagicMock()
    )
    
    # Should fallback deterministically
    assert "explain your understanding" in result.question
    assert result.type == "follow-up"
