"""
Purpose:
Defines Pydantic models for interview question generation.

Responsibilities:
- Strongly type the input strategy coming from the Agent.
- Validate the generated question output from the LLM.
- Provide safe fallback behaviors.

Connected Files:
- app/schemas/contract.py
- app/services/question_generator.py

Important implementation notes:
- Field names match backend/shared/schemas/ai_api.json exactly.
- The fallback method prevents complete API failure if LLM parsing completely fails.
"""

from typing import List, Optional

from pydantic import BaseModel, Field

from app.schemas.contract import RetrievedChunk


class QuestionStrategy(BaseModel):
    """The execution plan for the next question, determined by the Interview Agent."""
    day: int = Field(..., description="The curriculum day to cover")
    module: int = Field(..., description="The curriculum module")
    topic: str = Field(..., description="The main topic of the day")
    difficulty: str = Field(..., description="Target difficulty (easy/medium/hard)")
    concepts: List[str] = Field(default_factory=list, description="Specific concepts to probe")
    isFollowUp: bool = Field(False, description="Whether this is a follow up question")
    followUpOf: Optional[str] = Field(None, description="The ID of the previous question")


class FollowUpStrategy(BaseModel):
    """The execution plan for probing a candidate's previous weak answer."""
    day: int = Field(..., description="The curriculum day being evaluated")
    difficulty: str = Field(..., description="The difficulty level of the follow-up")
    previousAnswer: str = Field(..., description="The candidate's previous answer")
    weakConcepts: List[str] = Field(default_factory=list, description="Concepts the candidate missed")
    questionStrategy: Optional[QuestionStrategy] = Field(
        None, description="The strategy of the question being followed up on"
    )


class GeneratedQuestion(BaseModel):
    """The structured JSON payload generated by the LLM (ai_api.json 'question')."""
    question: str = Field(..., description="The wording of the question")
    type: str = Field("technical", description="The question type, usually 'technical'")
    difficulty: str = Field(..., description="The difficulty level")
    topic: str = Field(..., description="The main topic")
    day: int = Field(0, description="The curriculum day (always overwritten from the question strategy by the service)")
    expectedConcepts: List[str] = Field(default_factory=list, description="Key terms expected in the answer")
    retrievedContext: List[RetrievedChunk] = Field(default_factory=list)

    @classmethod
    def fallback(cls, strategy: Optional[QuestionStrategy] = None) -> "GeneratedQuestion":
        """
        Deterministic fallback when the LLM repeatedly fails to return valid JSON.
        Does not fabricate facts; generates a safe, generic technical question.
        """
        topic = strategy.topic if strategy else "technical concepts"
        diff = strategy.difficulty if strategy else "medium"
        concepts = strategy.concepts if strategy else []
        day = strategy.day if strategy else 0

        return cls(
            question=f"Could you explain your understanding of {topic}?",
            type="technical",
            difficulty=diff,
            topic=topic,
            day=day,
            expectedConcepts=concepts
        )
