"""
Purpose:
Defines Pydantic models for interview question generation.

Responsibilities:
- Strongly type the input strategy coming from the Agent.
- Validate the generated question output from the LLM.
- Provide safe fallback behaviors.

Connected Files:
- app/services/question_generator.py

Important implementation notes:
- The fallback method prevents complete API failure if LLM parsing completely fails.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class QuestionStrategy(BaseModel):
    """The execution plan for the next question, determined by the Interview Agent."""
    day: int = Field(..., description="The curriculum day to cover")
    module: int = Field(..., description="The curriculum module")
    topic: str = Field(..., description="The main topic of the day")
    difficulty: str = Field(..., description="Target difficulty (e.g., 'easy', 'medium', 'hard')")
    concepts: List[str] = Field(default_factory=list, description="Specific concepts to probe")
    isFollowUp: bool = Field(False, description="Whether this is a follow up question")
    followUpOf: Optional[str] = Field(None, description="The ID of the previous question")


class FollowUpStrategy(BaseModel):
    """The execution plan for probing a candidate's previous weak answer."""
    day: int = Field(..., description="The curriculum day being evaluated")
    topic: str = Field(..., description="The main topic of the conversation")
    weakConcepts: List[str] = Field(default_factory=list, description="Specific concepts the candidate missed")
    reasoningGaps: str = Field(..., description="Explanation of what was missing in the candidate's answer")


class GeneratedQuestion(BaseModel):
    """The structured JSON payload generated by the LLM."""
    question: str = Field(..., description="The wording of the question")
    type: str = Field(..., description="The question type, usually 'technical'")
    difficulty: str = Field(..., description="The difficulty level")
    topic: str = Field(..., description="The main topic")
    expectedConcepts: List[str] = Field(..., description="Key terms expected in the answer")

    @classmethod
    def fallback(cls, strategy: Optional[QuestionStrategy] = None) -> "GeneratedQuestion":
        """
        Deterministic fallback when the LLM repeatedly fails to return valid JSON.
        Does not fabricate facts; generates a safe, generic technical question.
        """
        topic = strategy.topic if strategy else "technical concepts"
        diff = strategy.difficulty if strategy else "medium"
        concepts = strategy.concepts if strategy else []
        
        return cls(
            question=f"Could you explain your understanding of {topic}?",
            type="technical",
            difficulty=diff,
            topic=topic,
            expectedConcepts=concepts
        )
